create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists visitors_created_at_idx on public.visitors (created_at desc);

alter table public.visitors enable row level security;

-- API writes use the server-side service role key, so no anon/authenticated policies are required.
